# Generated by Django 2.2.4 on 2020-05-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAuthors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
